version: '3.1' # if no version is specified then v1 is assumed. Recommended v2 minimum

services: # containers. same as docker run
  servicename: # a friendly name. This is also DNS name inside network
    image: # Optional if use build
    command: # Optional, replace the default CMD specified by the image
    environment: # Optional, same as -e in docker run
    volumes: # Optional, same as -v in docker run
  servicename2: 
   
volumes: # Optional, same as docker volume create

networks: # Optional, same as docker network create